### ISSUE TITLE
[Question] Job execution size 

### ISSUE THREAD

**Issue by aRn0D** [akeneo/BatchBundle#55]
When I execute a custom job the read, process, and write are executed several times but I just want to execute them one time. I found `batch_path` parameter set it to 1 but it does not change anything. Is it possible to manage it by the configuration?

My configuration
```yaml
connector:
    name: My connector
    jobs:
        ez_product_export:
            title: title
            type:  export
            steps:
                export_attribute:
                    title: title
                    services:
                        reader: connector.reader.attribute
                        processor: connector.processor.attribute
                        writer: connector.writer.attribute
                    parameters:
                        batch_size: 1
```

Thx!
